name: Build Debug APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Generate and Rename APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Extract versionName from build.gradle
        id: version
        run: |
          VERSION_NAME=$(grep versionName app/build.gradle.kts | sed 's/.*"\(.*\)".*/\1/')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Rename APK with version
        run: |
          mkdir -p renamed-apk
          cp app/build/outputs/apk/debug/app-debug.apk renamed-apk/SWAPI_App_${{ env.VERSION_NAME }}.apk

      - name: Upload Renamed APK
        uses: actions/upload-artifact@v4
        with:
          name: SWAPI_App_Debug
          path: renamed-apk/SWAPI_App_${{ env.VERSION_NAME }}.apk
